Add 1.4.0 to readme compatibility matrix
vmware-tanzu/velero-plugin-for-vsphere pull request #480
Opened 2022-08-25 23:54 UTC by xinyanw409

**What this PR does / why we need it**:
This PR added 1.4.0 to readme compatibility matrix.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add 1.4.0 to readme compatibility matrix.
```

2022-08-26 03:10 UTC, svcbot-qecnsdp commented
Congratulations !! 

All the pre-check tests passed
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/746/

2022-08-30 22:09 UTC, xing-yang commented on docs/guest.md
> +| 1.4.0                             | 7.0U1c/P02 - 7.0U3 | 1.19-1.21          | Bundled with TKGS          | 1.8.1          | No         | N/A
I thought 1.22 is tested.

2022-08-30 22:09 UTC, xing-yang commented on docs/supervisor.md
> +| 1.4.0                             | 7.0U1c/P02 - 7.0U3 | Bundled with vSphere (1.16-1.19, 1.18-1.20, 1.19-1.21)            | Bundled with vSphere       | 1.8.1          | No         | N/A
K8s 1.22 should be tested.

2022-09-06 18:22 UTC, rpanduranga requested changes

2022-09-06 18:22 UTC, rpanduranga commented on docs/vanilla.md
> +| 1.4.0                             | 6.7U3 P06 - 7.0U3      | 1.20-1.23          | 2.2.2, 2.3.1, 2.4.1, 2.5.1 | 1.8.1          | No         | N/A
CSI 2.6 is also supported and validated

2022-09-06 18:22 UTC, rpanduranga commented on docs/supervisor.md
> +| 1.4.0                             | 7.0U1c/P02 - 7.0U3 | Bundled with vSphere (1.16-1.19, 1.18-1.20, 1.19-1.21)            | Bundled with vSphere       | 1.8.1          | No         | N/A
K8s 1.22 is tested

2022-09-06 18:22 UTC, rpanduranga commented on docs/guest.md
> +| 1.4.0                             | 7.0U1c/P02 - 7.0U3 | 1.19-1.21          | Bundled with TKGS          | 1.8.1          | No         | N/A
k8s 1.22 is tested

2022-09-08 02:13 UTC, rpanduranga approved these changes

2022-09-08 17:40 UTC, deepakkinni approved these changes

2022-09-08 17:42 UTC, merged